Create Campaigns_CampaignMembers.recipe.yml
SFDO-Community-Sprints/Snowfakery-Recipe-Templates pull request #84
Opened 2021-11-18 03:30 UTC by alisamhh

Basic working recipe 🎉🎉🎉

# Critical Changes

# Changes

# Issues Closed

2021-11-23 20:29 UTC, programmer2coder requested changes
Hey @alisamhh , this ran without errors when I tested it, yet I added some suggestions in the comments. Have a look and decide.

2021-11-27 03:53 UTC, acrosman commented on snowfakery_samples/salesforce/Campaigns_CampaignMembers.recipe.yml
> +      fake: bs
Since department is not a needed field in this example, I suggest removing it entirely instead of trying to find a valid faker for it.

2022-01-05 20:41 UTC, alisamhh commented on snowfakery_samples/salesforce/Campaigns_CampaignMembers.recipe.yml
> +    name:
Thanks! I've made this change.

2022-01-05 20:42 UTC, alisamhh commented on snowfakery_samples/salesforce/Campaigns_CampaignMembers.recipe.yml
> +    name:
Thanks! I've made this change.

2022-01-05 20:42 UTC, alisamhh commented on snowfakery_samples/salesforce/Campaigns_CampaignMembers.recipe.yml
> +      fake: bs
Thanks! I've made this change.

2022-01-05 20:42 UTC, alisamhh commented on snowfakery_samples/salesforce/Campaigns_CampaignMembers.recipe.yml
> +  count: 1
Thanks! I've made this change.

2022-01-05 20:43 UTC, alisamhh commented
@programmer2coder @eehjunggnujhee Thanks for your patience! These changes have now been done. Could you please review?

2022-01-11 20:33 UTC, programmer2coder approved these changes

2022-01-11 20:51 UTC, merged

2022-01-13 14:43 UTC, programmer2coder commented
@alisamhh I tested it and it all looks good.  Yeah!  Another official entry into the Snowfakery samples repo!

2022-01-13 18:54 UTC, alisamhh commented
Yay!! Thanks 😊

On Fri, 14 Jan 2022 at 3:43 AM, programmer2coder ***@***.***>
wrote:

> @alisamhh <https://github.com/alisamhh> I tested it and it all looks
> good. Yeah! Another official entry into the Snowfakery samples repo!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/84#issuecomment-1012200588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJINWNMYYPCXIOPNXGFZQEDUV3QKRANCNFSM5IISLV3Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/84/c1012200588@
> github.com>
>