Feature/campaign member
SFDO-Community-Sprints/Snowfakery-Recipe-Templates pull request #86
Opened 2021-11-18 04:19 UTC by JodieM

# Critical Changes
Recipe for NPSP Contacts, Campaign, Campaign Member Status and Campaign Members

# Changes
New Recipe

# Issues Closed
#50

2021-11-18 04:20 UTC, JodieM commented
@acrosman not sure if we need to merge both @alisamhh and mine or create a new Issue?

2021-11-19 00:39 UTC, acrosman commented
We can have them both committed and attached to the same issue that's fine. Hopefully I'll have some time to review and test both the weekend if someone else doesn't get there faster. 

Thank you again for coming to the sprint and participating. Looking forward to seeing you again sometime.

2021-11-23 19:58 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +## NPSP Contact Campaign Campaigin Member Example
typo Campaigin  --> Campaign

2021-11-23 19:59 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +# The Contacts to the Campaign with one of the Campaign Member Statuses randomly chosen.
Contacts to --> Contacts are added to

2021-11-23 19:59 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +# snowfakery snowfakery snowfakery_samples\npsp\Contact_Campaign_CampaignMember.recipe.yml --target-number 5 Contact --output-format json --output-file snowfakery_samples/temp/output.json
at the beginning of this line, you have an extra "snowfakery" word that should not be there

2021-11-23 20:02 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +# If you're not familiar with NPSP, there is automation to populate the standard Email and Phone fields based on the data below.
Yeah!  This is a good reminder! thanks.

2021-11-23 20:04 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +    Name: ${{fake.Bs}} Campaign
this would look better with output Capitalized (like with CatchPhrase?  Jung is looking up how to do this)

2021-11-23 20:05 UTC, programmer2coder commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +# 1-2. CampaingMemberStatus (2)
typo CampaingMemberStatus  --> CampaignMemberStatus

2021-11-23 20:28 UTC, programmer2coder requested changes
Hey @JodieM , this ran without errors when I tested it, yet I added some suggestions in the comments. Have a look and decide.

2021-11-27 04:07 UTC, acrosman commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +    Name: ${{fake.Bs}} Campaign
It could _be_ done with: `${{fake.bs.__str__().title()}} Campaign`, but calling `__` functions directly is frowned upon. I'm interested to know if @prescod thinks something like `${{str(fake.bs).title()}}` _should_ work (it doesn't in my testing) or if he has a suggestion about how to do string case manipulations in recipes.

2021-12-01 00:54 UTC, prescod commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +    Name: ${{fake.Bs}} Campaign
Snowfakery is built on Jinja and Jinja has a syntax for transformations which seems to work:

```
- object: Campaign
  fields:
    Name: ${{fake.bs | title}} Campaign
    UpperCaseName: ${{fake.bs | upper}}
    LowerCaseName: ${{fake.bs | lower}}
  ```

https://github.com/SFDO-Tooling/Snowfakery/pull/554

2021-12-01 00:56 UTC, JodieM commented on snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml
> +    Name: ${{fake.Bs}} Campaign
Excellent thanks @prescod, I will try that out!

2021-12-07 07:26 UTC, JodieM commented
@acrosman I made the changes, and the new Title Case Campaign works really well. I have uploaded the new file on this branch. Do I need to do anything more to get this PR ready for merge now?

2021-12-08 17:30 UTC, acrosman commented
@JodieM thanks for the changes.  One of us just needs to find the time to re-run to make sure we didn't miss any typos or similar slipping through.  @programmer2coder any chance you have time to re-check?  I'll try to get there when I have a few minutes to focus on not-work when not-fried.

2021-12-13 23:51 UTC, eehjunggnujhee commented
Hi @programmer2coder 
Snowfakery prioritizes certain objects based on the standardized order of inserts recommended by Salesforce. @prescod  You have mentioned before that there is a way to override the default order of insert.

2021-12-14 21:07 UTC, programmer2coder commented
Thanks @eehjunggnujhee  , I tried finding that in Snowfakery documentation but couldn't, so I just posted the question in CumulusCI (CCI) community (figuring @prescod is pretty busy these days).

2021-12-17 16:51 UTC, eehjunggnujhee commented
@programmer2coder  the syntax looks like what it will going to do. I can do test from my side and update here

2021-12-22 02:36 UTC, eehjunggnujhee commented
@programmer2coder hi~ using loading file as an option for generate_and_load_from_yml worked. sample command below:
```
cci task run generate_and_load_from_yaml -o generator_yaml snowfakery_samples/npsp/Contact_Campaign_CampaignMember.recipe.yml -o num_records 10 -o num_records_tablename Contact --org dev --loading_rules snowfakery_samples/npsp/CampaignMember_Status.mapping.yml
```

The loading file is currently in my local machine. We can perhaps discuss where to host these types of files in the repo.

```
- sf_object: CampaignMemberStatus
  load_after: Contact

- sf_object: CampaignMember
  load_after: CampaignMemberStatus
```
Thank you
<img width="776" alt="load file" src="https://user-images.githubusercontent.com/33381679/147025579-a190f83b-b783-4317-b164-05f21e665d6e.png">

2021-12-22 04:19 UTC, prescod commented
There is another way to solve this. As discussed above, Snowfakery infers the order from what happens in the recipe. You can make the implicit dependency between CampaignMember and CampaignMemberStatus explicit and it will force CampaignMemberStatus to load before CampaignMember. Here's how I did that:

```
- object: CampaignMember
  fields:
    ContactId:
      reference: Contact
    Status:       
      random_choice:
       - Sent
       - Responded
       - Attended
       - On List
    CampaignId: 
      reference: Campaign
    __depends_upon:  # forces the correct load order
      reference: CampaignMemberStatus  
- object: CampaignMember
  fields:
    ContactId:
      reference: Contact
    Status:       
      random_choice:
       - Sent
       - Responded
       - Attended
       - On List
    CampaignId: 
      reference: Campaign
    __depends_upon:  # forces the correct load order
      reference: CampaignMemberStatus  
```

There is nothing special about the word __depends_upon: you could also call it __foobar or __load_after. The leading underscores make it so that it won't output an actual field for loading into Salesforce. But the reference will nevertheless be observed and will force a load order change.

So that's an alternate way to do it which does not require an external file.

2021-12-22 04:28 UTC, JodieM commented
Fabulous! I will change it to that.


On Wed, Dec 22, 2021, 3:19 PM Paul Prescod ***@***.***> wrote:

> There is another way to solve this. As discussed above, Snowfakery infers
> the order from what happens in the recipe. You can make the implicit
> dependency between CampaignMember and CampaignMemberStatus explicit and it
> will force CampaignMemberStatus to load before CampaignMember. Here's how I
> did that:
>
> - object: CampaignMember
>   fields:
>     ContactId:
>       reference: Contact
>     Status:
>       random_choice:
>        - Sent
>        - Responded
>        - Attended
>        - On List
>     CampaignId:
>       reference: Campaign
>     __depends_upon:  # forces the correct load order
>       reference: CampaignMemberStatus
> - object: CampaignMember
>   fields:
>     ContactId:
>       reference: Contact
>     Status:
>       random_choice:
>        - Sent
>        - Responded
>        - Attended
>        - On List
>     CampaignId:
>       reference: Campaign
>     __depends_upon:  # forces the correct load order
>       reference: CampaignMemberStatus
>
> There is nothing special about the word __depends_upon: you could also
> call it __foobar or __load_after. The leading underscores make it so that
> it won't output an actual field for loading into Salesforce. But the
> reference will nevertheless be observed and will force a load order change.
>
> So that's an alternate way to do it which does not require an external
> file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/86#issuecomment-999274664>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAWUIN3XL64XCSP33AM5XK3USFGW5ANCNFSM5IIUJBJA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/86/c999274664@
> github.com>
>

2022-01-30 01:51 UTC, JodieM commented
Ok just getting back to this after a long time... 

The bottom of my recipe now says

```
- object: CampaignMember 
  fields:
    ContactId:
      reference: Contact
    Status:       
      random_choice:
       - Sent
       - Responded
       - Attended
       - On List
    CampaignId: 
      reference: Campaign
    __depends_upon:  # forces the correct load order but doesn't output a field
      reference: CampaignMemberStatus 
```

However I get the error 

```
Error: Problem rendering field __depends_upon:
 Cannot evaluate function `reference`:
 Cannot find an object named CampaignMemberStatus
```

I also tried naming it "__load_after" but it had the same issue

Also, I did not get the issue where it did not create Campaign Members with the newly created CM Statuses on the first run. It seemed to have one of each on the first run. 

Sorry, but I'm a bit stuck with where to go next.

2022-01-30 05:10 UTC, eehjunggnujhee commented
Hi @JodieM  Take the CampaignMemberStatus out from the friends relationship and put it in the same hierarchy as campaign member.

```

- object: Campaign
  just_once: True
  fields: 
    Name: ${{fake.Bs | title}} Campaign
    Type:
      random_choice:
        - Conference
        - Webinar
        - Email
        - Telemarketing    
    Status: In Progress
    IsActive: True
    Description:
      fake.text:
        max_nb_chars: 100
    StartDate:
      date_between:
        start_date: -30d
        end_date: today
    EndDate: ${{fake.FutureDate}}        

- object: CampaignMemberStatus
  nickname: cm1
  fields: 
    CampaignId:
      reference: Campaign
    Label: On List
    HasResponded: False
- object: CampaignMemberStatus
  nickname: cm2
  fields: 
    CampaignId:
      reference: Campaign
    Label: Attended
    HasResponded: True

- object: CampaignMember
  fields:
    ContactId:
      reference: Contact
    Status:       
      random_choice:
        - Sent
        - Responded
        - Attended
        - On List
    CampaignId: 
      reference: Campaign
    __depends_upon:  # forces the correct load order
        reference: CampaignMemberStatus  
```

2022-01-30 22:00 UTC, JodieM commented
Aha, that makes much more sense now. Ok I will get onto it soon.

On Sun, Jan 30, 2022, 4:10 PM eehjunggnujhee ***@***.***>
wrote:

> Hi @JodieM <https://github.com/JodieM> Take the CampaignMemberStatus out
> from the friends relationship and put it in the same hierarchy as campaign
> member.
>
>
> - object: Campaign
>   just_once: True
>   fields:
>     Name: ${{fake.Bs | title}} Campaign
>     Type:
>       random_choice:
>         - Conference
>         - Webinar
>         - Email
>         - Telemarketing
>     Status: In Progress
>     IsActive: True
>     Description:
>       fake.text:
>         max_nb_chars: 100
>     StartDate:
>       date_between:
>         start_date: -30d
>         end_date: today
>     EndDate: ${{fake.FutureDate}}
>
> - object: CampaignMemberStatus
>   nickname: cm1
>   fields:
>     CampaignId:
>       reference: Campaign
>     Label: On List
>     HasResponded: False
> - object: CampaignMemberStatus
>   nickname: cm2
>   fields:
>     CampaignId:
>       reference: Campaign
>     Label: Attended
>     HasResponded: True
>
> - object: CampaignMember
>   fields:
>     ContactId:
>       reference: Contact
>     Status:
>       random_choice:
>         - Sent
>         - Responded
>         - Attended
>         - On List
>     CampaignId:
>       reference: Campaign
>     __depends_upon:  # forces the correct load order
>         reference: CampaignMemberStatus
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/86#issuecomment-1025071885>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAWUINZ7PMTSTXMRW25HKU3UYTB6BANCNFSM5IIUJBJA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <SFDO-Community-Sprints/Snowfakery-Recipe-Templates/pull/86/c1025071885@
> github.com>
>

2022-03-07 02:06 UTC, eehjunggnujhee submitted a review, later dismissed
@JodieM  Many questions addressed in this recipes were resolved by the snowfakery latest update. CampaignMemberStatus are inserted before Campaign Member. Merging this request. Thank you

2022-03-07 02:07 UTC, eehjunggnujhee commented
@programmer2coder Hi! you are the last reviewer! the recipe ran as expected. I also updated the CCI CLI to the latest version. Let me know what you think, I think we are ready to merge this ticket

2022-04-05 22:48 UTC, programmer2coder commented
Yes, I have just tested this and the recipe ran as expected.  Newly created campaign members are randomly assigned to both the 2 new statuses as well as the 2 old statuses.  Great!

2022-04-05 22:49 UTC, programmer2coder approved these changes

2022-04-05 22:51 UTC, merged