Feature/npsp ocr2
SFDO-Community-Sprints/Snowfakery-Recipe-Templates pull request #91
Opened 2021-12-27 04:39 UTC by allisonletts

# Critical Changes
- restructures for clearer relationships

# Changes

# Issues Closed
fixes #89

2021-12-28 18:28 UTC, jesslopez-sf requested changes
@allisonletts - the recipe worked like a charm! I added some super minor suggestions, mainly around the commands you would use to run the recipe. The name of the recipe file didn't match and the directory to output the temp json file was also changed. Otherwise, great job! :)

2021-12-28 18:28 UTC, jesslopez-sf commented on snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
> +# cci task run snowfakery --recipe snowfakery_samples/npsp/Opportunity_npsp_soft_credits.yml
```suggestion
# cci task run snowfakery --recipe snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
```

2021-12-28 18:28 UTC, jesslopez-sf commented on snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
> +# snowfakery --output-format json --output-file src/foo.json snowfakery_samples/npsp/Opportunity_npsp_soft_credits.yml
```suggestion
# snowfakery --output-format json --output-file snowfakery_samples/temp/output.json snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
```

2021-12-28 18:28 UTC, jesslopez-sf commented on snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
> +# The account
Not sure if this was a comment left over from the original recipe or if part of it was accidentally deleted?

2021-12-30 20:58 UTC, allisonletts commented on snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml
> +# The account
whoops! Thanks!

2022-01-03 14:59 UTC, jesslopez-sf approved these changes
Awesome. Thank you! :)

2022-01-03 15:00 UTC, merged